# kb apply -f ~/ronin/gke/kubernetes_resources/service_account_rbac.yaml
---
# Service account the client will use to reset the deployment,
# by default the pods running inside the cluster can do no such things.
kind: ServiceAccount
apiVersion: v1
metadata:
  name: ronin-cronjob
  namespace: default
---
# allow getting status and patching only the one deployment you want
# to restart
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ronin-cronjob
  namespace: default
rules:
  - apiGroups: ["apps", "extensions", "autoscaling", "snapshot.storage.k8s.io"]
    resources: ["*"]
    verbs: ["*"]
---
# bind the role to the service account
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ronin-cronjob
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ronin-cronjob
subjects:
  - kind: ServiceAccount
    name: ronin-cronjob
    namespace: default